version: '3.1'

services:
  db-postgresql:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: adminT&gsww1987
    volumes:
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'

  web:
    depends_on:
      - db-postgresql
    image: tomcat
    volumes:
      - ./build/libs/utility-meter-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/ROOT.war
    ports:
      - '8080:8080'