version: '3.8'

services:
  db:
    image: postgres:alpine
    restart: always
    container_name: postgres_host
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: 123456

    ports:
      - '5432:5432'
  #    volumes:
  #      - db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - '8089:8080'

#  app:
#    build: docker
#    restart: unless-stopped
#    container_name: app
#    #    контейнер не запустится, пока не поднимется db
#    depends_on:
#      - db
#    ports:
#      - '8080:8080'
