CREATE USER pp WITH PASSWORD '123';
CREATE DATABASE ppdb;
GRANT ALL PRIVILEGES ON DATABASE ppdb TO pp;
\connect ppdb;
CREATE SCHEMA company;
GRANT ALL PRIVILEGES ON SCHEMA company TO pp;
CREATE SCHEMA service_liquibase;
GRANT ALL PRIVILEGES ON SCHEMA service_liquibase TO pp;